#!/bin/sh
set -e

[ -n "${IPKG_INSTROOT}" ] && exit 0

/etc/init.d/opera-proxy enable  >/dev/null 2>&1 || true
/etc/init.d/opera-proxy restart >/dev/null 2>&1 || /etc/init.d/opera-proxy start >/dev/null 2>&1 || true
/etc/init.d/rpcd reload         >/dev/null 2>&1 || true
rm -f /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
