#!/bin/sh
set -e

[ -n "${IPKG_INSTROOT}" ] && exit 0

/etc/init.d/opera-proxy stop    >/dev/null 2>&1 || true
/etc/init.d/opera-proxy disable >/dev/null 2>&1 || true
rm -f /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
